name: kpop_application
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0-47.0.dev

dependencies:
  flutter:
    sdk: flutter
  bloc: ^8.1.1
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  equatable: ^2.0.7
  surf_lint_rules: ^3.1.0
  # dio: ^5.0.0
  provider: ^6.1.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


flutter:
  uses-material-design: true
